version: 2
updates:
  - package-ecosystem: docker
    directory: /8.1-fpm
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']

  - package-ecosystem: docker
    directory: /8.5-fpm
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']

  - package-ecosystem: docker
    directory: /httpd
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']
