ProxyTimeout 600

RemoteIPHeader CF-Connecting-IP

ServerName default-server.docker.internal

ServerSignature Off
ServerTokens Prod

<FilesMatch ".+\.ph(ar|p|tml)$">
    SetHandler "proxy:fcgi://${PHP_FPM_HOST}:${PHP_FPM_PORT}"
</FilesMatch>

<FilesMatch ".+\.phps$">
	Require all denied
</FilesMatch>

<FilesMatch "^\.ph(ar|p|ps|tml)$">
	Require all denied
</FilesMatch>
