ServerName phpstack.docker.invalid

ServerSignature Off
ServerTokens Prod

ProxyTimeout 600

<FilesMatch ".+\.ph(ar|p|tml)$">
    SetHandler "proxy:fcgi://${PHP_FPM_HOST}:${PHP_FPM_PORT}"
</FilesMatch>

<FilesMatch ".+\.phps$">
	Require all denied
</FilesMatch>

<FilesMatch "^\.ph(ar|p|ps|tml)$">
	Require all denied
</FilesMatch>
