name: Cleanup GHCR Old Digests

on:
  schedule:
    - cron: '0 5 1 * *'
  workflow_dispatch:

jobs:
  cleanup:
    name: Remove old untagged image versions
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old untagged versions of phpstack
        uses: actions/delete-package-versions@v5
        with:
          package-name: phpstack
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 9
          delete-only-untagged-versions: true
